[[rules]]
    description = "Generic API key"
    regex = '''(?i)(api_key|apikey)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
    tags = ["key", "API", "generic"]

[[rules]]
    description = "Generic Secret"
    regex = '''(?i)(secret|password|pass|pw|key|token)(.{0,20})?['|"][0-9a-zA-Z]{32,64}['|"]'''
    tags = ["key", "Secret", "generic"]

[[rules]]
    description = "WP-Config"
    regex='''define(.{0,20})?(DB_CHARSET|NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_HOST|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY|DB_NAME|DB_USER)(.{0,20})?['|"].{10,120}['|"]'''
    tags = ["key", "API", "generic"]

[[rules]]
    description = "AWS Secret Key"
    regex = '''(?i)aws(.{0,20})?(?-i)['\"]?[0-9a-zA-Z\/+]{40}['\"]?'''
    tags = ["key", "AWS"]

[[rules]]
    description = "AWS Manager ID"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]

[[rules]]
    description = "Slack"
    regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
    tags = ["key", "Slack"]

[[rules]]
    description = "Slack Webhook"
    regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
    tags = ["key", "slack"]

[[rules]]
    description = "Stripe API key"
    regex = '''(?i)stripe(.{0,20})?['\"][sk|rk]_live_[0-9a-zA-Z]{24}'''
    tags = ["key", "Stripe"]

[[rules]]
	description = "Asymmetric Private Key"
	regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
	tags = ["key", "AsymmetricPrivateKey"]

[[rules]]
	description = "Files with keys and credentials"
    path = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass|pem|key|shadow)'''

[allowlist]
    description = "global allowlist"
    files = [
            '''^\.?gitleaks.toml$''',
            '''(.*?)(png|jpg|gif|doc|pdf|bin)$''',
            '''yarn.lock$''',
            '''(go.mod|go.sum)$'''
            ]
