version: 2.1
description: Security tooling steps

orbs:
  anchore: anchore/anchore-engine@1.5.0
  snyk: snyk/snyk@0.0.8

executors:
  container_builder:
    description: |
      Simple base image with orb-specific variables set
    docker:
    - image: circleci/buildpack-deps:stretch
    environment:
      ANCHORE_VERSION: "v0.4.1"
  anchore_engine:
    description: |
      Docker stable image with ANCHORE_VERSION environment variable set.
    docker:
    - image: docker:stable-git
    environment:
      ANCHORE_VERSION: v0.4.1

commands:
  parse:
    parameters:
      input_directory:
        default: ~/output
        type: string
        description: "The directory containing raw tool output"
      output_directory:
        default: ~/output/parsed_output
        type: string
        description: "The directory to save parsed tool output to."
    steps:
      - run:
          name: "[Parser] Create output folder"
          command: |
            mkdir -p << parameters.output_directory >> 
      - run:
          name: "[Parser] Download and install Python 3.7"
          command: |
            # # Check if it's possible to download Python 3.7 via the usual means.
            # if [[ ! $(which python3.7) ]]; then
            #   (set +o pipefail; sudo apk add python3.7 || sudo apt-get install -y python3.7 || sudo yum install -y python3.7)
            # fi

            # If it's still not available, we'll have to build it manually.
            if [[ ! $(which python3.7) ]]; then
              curl -O https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz
              tar -xf Python-3.7.4.tar.xz
              cd Python-3.7.4 && ./configure && make build_all && sudo make altinstall
            fi
      - run:
          name: "[Parser] Download and run parser"
          command: |
            git clone https://github.com/salidas/circleci-security-parser
            python3.7 circleci-security-parser/main.py -i << parameters.input_directory>> -o << parameters.output_directory >>
      - store_artifacts:
          path: << parameters.output_directory >>

  anchore_start_engine:
    parameters:
      timeout:
        type: string
        description: Length of time allocated before the build stops.
    steps:
      - run:
          name: "[Anchore] Starting the Anchore engine..."
          command: |
            ANCHORE_VERSION="${ANCHORE_VERSION}"
            TIMEOUT="<< parameters.timeout >>"
            docker run -d --name anchore-engine "anchore/inline-scan:${ANCHORE_VERSION}" start
            docker exec -e TIMEOUT="$TIMEOUT" -it anchore-engine bash -lc 'anchore_ci_tools.py --wait --timeout "$TIMEOUT"'

  anchore_scan_remote:
    parameters:
      image_name:
        type: string
        description: Image repository & tag (eg - "docker.io/anchore/anchore-engine:latest").
      timeout:
        type: string
        description: Length of time allocated before the build stops.
      private:
        default: false
        type: boolean
        description: The status of the remote registry
      username:
        default: $DOCKER_USER
        type: string
      password:
        default: $DOCKER_PASS
        type: string
      registry:
        default: docker.io
        type: string
    steps:
      - when:
          condition: << parameters.registry >>
          steps:
            - anchore/add_private_registry:
                registry_name: << parameters.registry >>
                registry_user: << parameters.username >>
                registry_pass: << parameters.password >>
      - run:
          name: "[Anchore] Scanning remote image"
          command: |
            IMAGE_NAME="<< parameters.image_name >>"
            TIMEOUT="<< parameters.timeout >>"
            docker exec -e IMAGE_NAME="$IMAGE_NAME" -e TIMEOUT="$TIMEOUT" -it anchore-engine bash -lc 'anchore_ci_tools.py --analyze --report --image "$IMAGE_NAME" --timeout "$TIMEOUT"'
            docker exec -e IMAGE_NAME="$IMAGE_NAME" -it anchore-engine bash -lc 'anchore-cli image get "$IMAGE_NAME"'
            docker cp anchore-engine:/anchore-engine/anchore-reports/ ./
      - anchore/parse_reports
      - run:
          name: "[Anchore] Move output artifacts to a consistent location"
          command: |
            mkdir -p ~/output/anchore
            mv anchore-reports/* ~/output/anchore/
      - store_artifacts:
          path: ~/output/anchore

  anchore_scan_local:
    parameters:
      image_name:
        type: string
        description: Image name & tag, e.g. "anchore-engine:latest".
      timeout:
        type: string
        description: Length of time allocated before the build stops.
      dockerfile:
        type: string
        description: The path to the Dockerfile used to build the local image
        default: ""
      policy:
        type: string
        description: Anchore security policy to compare the scan results against
        default: "${HOME}/project/.circleci/.anchore/policy_bundle.json"
    steps:
      - run:
          name: "[Anchore] Scanning local image"
          command: |
            if [[ ! $(which bash) ]]; then
              (set +o pipefail; apk add bash || apt-get install -y bash || yum install -y bash)
            fi
            if [[ ! $(which curl) ]]; then
              (set +o pipefail; apk add curl || apt-get install -y curl || yum install -y curl)
            fi

            POLICY_FAILURE="false"

            # Because this is in a command, I have to use a magic variable to store the Anchore version
            ANCHORE_VERSION="v0.4.1"

            TIMEOUT="<< parameters.timeout >>"
            POLICY_BUNDLE_PATH="<< parameters.policy >>"
            DOCKERFILE_PATH="<< parameters.dockerfile >>"
            IMAGE_NAME="<< parameters.image_name >>"

            run_cmd="curl -s https://ci-tools.anchore.io/inline_scan-${ANCHORE_VERSION} | bash -s -- -r -t $TIMEOUT"
            if $POLICY_FAILURE; then
              run_cmd="$run_cmd -f"
            fi
            if [[ ! -z $POLICY_BUNDLE_PATH ]] && [[ -f $POLICY_BUNDLE_PATH ]]; then
              run_cmd="$run_cmd -b $POLICY_BUNDLE_PATH"
            else
              echo "ERROR - could not find policy bundle $POLICY_BUNDLE_PATH - using default policy bundle."
            fi
            if [[ ! -z $DOCKERFILE_PATH ]] && [[ -f $DOCKERFILE_PATH ]]; then
              run_cmd="$run_cmd -d $DOCKERFILE_PATH"
            else
              echo "ERROR - could not find Dockerfile $DOCKERFILE_PATH - Dockerfile not included in scan."
            fi
            run_cmd="$run_cmd $IMAGE_NAME"
            eval "$run_cmd"
      - anchore/parse_reports
      - run:
          name: "[Anchore] Move output artifacts to a consistent location"
          command: |
            mkdir -p ~/output/anchore
            mv anchore-reports/* ~/output/anchore/
      - store_artifacts:
          path: ~/output/anchore

  detect-secrets_scan:
    parameters:
      directory:
        default: /home/circleci/project
        type: string
        description: The directory to run detect-secrets on
    steps:
      - run:
          name: "[detect-secrets] Install and run detect-secrets"
          command: |
            mkdir -p ~/output/detect-secrets
            pip install --user detect-secrets
            detect-secrets scan << parameters.directory >> | tee ~/output/detect-secrets/results_detect-secrets.json
      - store_artifacts:
          path: ~/output/detect-secrets

  dumpsterdiver_retrieve:
    parameters:
      installation_directory:
        default: ~/dumpsterdiver
        type: string
        description: The location to download DumpsterDiver to
    steps:
      - run:
          name: "[DumpsterDiver] Clone from GitHub repository"
          command: git clone https://github.com/securing/DumpsterDiver << parameters.installation_directory >>
      - run:
          name: "[DumpsterDiver] Install requirements"
          command: sudo apt-get install python3-dev && pip install --user -r << parameters.installation_directory >>/requirements.txt

  dumpsterdiver_scan:
    parameters:
      directory:
        default: ~/project
        type: string
        description: The directory to run DumpsterDiver on.
      installation_directory:
        default: ~/DumpsterDiver
        type: string
        description: The location where DumpsterDiver is
    steps:
      - run:
          name: "[DumpsterDiver] Create directory to store results"
          command: mkdir -p ~/output/dumpsterdiver
      - run:
          name: "[DumpsterDiver] Search for standard findings"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_standard.json -p << parameters.directory >> -s -a
      - run:
          name: "[DumpsterDiver] Search for AWS Keys (1)"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_aws_1.json -p << parameters.directory >> --grep-words *aws_access_key_id* *aws_secret_access_key*
      - run:
          name: "[DumpsterDiver] Search for AWS Keys (2)"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_aws_2.json -p << parameters.directory >> --min-key 40 --max-key 40 --entropy 4.3
      - run:
          name: "[DumpsterDiver] Search for Azure Keys"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_azure.json -p << parameters.directory >> --min-key 66 --max-key 66 --entropy 5.1
      - run:
          name: "[DumpsterDiver] Search for Private Keys"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_private_keys.json -p << parameters.directory >> --min-key 76 --max-key 76 --entropy 5.1
      - run:
          name: "[DumpsterDiver] Search for passwords (minimum eight, complexity seven)"
          command: |
            cd ~/dumpsterdiver
            python DumpsterDiver.py -o ~/output/dumpsterdiver/results_dumpsterdiver_passwords.json -p << parameters.directory >> --min-pass 8 --max-pass 20 --pass-complex 7
      - store_artifacts:
          path: ~/output/dumpsterdiver

  snyk_image_scan:
    parameters:
      image_name:
        type: string
        description: The container image to be scanned by Snyk
      fail_on_issues:
        default: false
        type: boolean
        description: Should the build fail if vulns have been found?
      monitor_on_build:
        default: false
        type: boolean
        description: Determine whether the image should be monitored on snyk.io after scan
      snyk_token:
        default: SNYK_TOKEN
        type: string
        description: The environment variable containing the snyk.io API token
    steps:
      - run:
          name: "[Snyk] Install build pre-requisites"
          command: |
            if [[ ! $(which bash) ]]; then
              (set +o pipefail; apk add bash || apt-get install -y bash || yum install -y bash)
            fi
            if [[ ! $(which curl) ]]; then
              (set +o pipefail; apk add curl || apt-get install -y curl || yum install -y curl)
            fi
            if [[ ! $(which sudo) ]]; then
              (set +o pipefail; apk add sudo || apt-get install -y sudo || yum install -y sudo)
            fi
            mkdir -p ~/output/snyk
      - snyk/scan:
          docker-image-name: << parameters.image_name >>
          fail-on-issues: << parameters.fail_on_issues >>
          monitor-on-build: << parameters.monitor_on_build >>
          token-variable: << parameters.snyk_token >>
          additional-variables: "--json > ~/output/snyk"
      - store_artifacts:
          path: ~/output/snyk

jobs:
  # Check a directory for any secrets such as private keys, API keys, etc.
  secrets:
    docker:
      - image: circleci/python:3.6.9
    parameters:
      directory:
        default: /home/circleci/project
        type: string
        description: The directory to run secrets detection tools on.
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - dumpsterdiver_retrieve
      - dumpsterdiver_scan:
          directory: << parameters.directory >>
      - detect-secrets_scan:
          directory: << parameters.directory >>
      - parse

  # node-dependencies:
  #   docker:
  #     - image: circleci/node:4.8.2

  # Scan a locally built container image.
  container-local:
    executor: container_builder
    parameters:
      image_name:
        type: string
        description: Image name & tag, e.g. "anchore-engine:latest".
      timeout:
        type: string
        description: Length of time allocated before the build stops.
      dockerfile:
        type: string
        description: Dockerfile associated with local build
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - snyk_image_scan:
          image_name: << parameters.image_name >>
      - anchore_start_engine:
          timeout: << parameters.timeout >>
      - anchore_scan_local:
          image_name: << parameters.image_name >>
          timeout: << parameters.timeout >>
          dockerfile: << parameters.dockerfile >>
      - parse

  # Scan a container image hosted remotely in a public or private registry
  container-remote:
    executor: container_builder
    parameters:
      image_name:
        type: string
        description: Image org, name & tag (eg - "anchore/anchore-engine:latest").
      timeout:
        default: "600"
        type: string
        description: Length of time allocated before the build stops.
      private:
        default: false
        type: boolean
        description: The status of the remote registry
      username:
        default: $DOCKER_USER
        type: string
      password:
        default: $DOCKER_PASS
        type: string
      registry:
        default: docker.io
        type: string
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "[Snyk] Pull remote image in preparation for Snyk scan"
          command: |
            docker pull << parameters.registry >>/<< parameters.image_name >>
      - snyk_image_scan:
          image_name: << parameters.image_name >>
      - anchore_start_engine:
          timeout: << parameters.timeout >>
      - anchore_scan_remote:
          image_name: << parameters.image_name >>
          timeout: << parameters.timeout >>
          private: << parameters.private >>
          username: << parameters.username >>
          password: << parameters.password >>
          registry: << parameters.registry >>
      - parse